// <auto-generated />
using System;
using CaritasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaritasAPI.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20181110113511_IntialConfiguration")]
    partial class IntialConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaritasAPI.Models.Gender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("genderName");

                    b.HasKey("id");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("CaritasAPI.Models.Nationalities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nationalityName");

                    b.HasKey("id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("CaritasAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<int?>("genderid");

                    b.Property<string>("lastName");

                    b.Property<string>("name");

                    b.Property<int?>("nationalityid");

                    b.Property<int>("oib");

                    b.Property<string>("phoneNumber");

                    b.HasKey("id");

                    b.HasIndex("genderid");

                    b.HasIndex("nationalityid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CaritasAPI.Models.User", b =>
                {
                    b.HasOne("CaritasAPI.Models.Gender", "gender")
                        .WithMany("users")
                        .HasForeignKey("genderid");

                    b.HasOne("CaritasAPI.Models.Nationalities", "nationality")
                        .WithMany("users")
                        .HasForeignKey("nationalityid");
                });
#pragma warning restore 612, 618
        }
    }
}
